// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCujgUVu3pinxOeKzN0JtRulPbnJxHIgc',
    appId: '1:1050359172710:web:5b40d0f3737f0f4c6467a7',
    messagingSenderId: '1050359172710',
    projectId: 'bitsmultiservice',
    authDomain: 'bitsmultiservice.firebaseapp.com',
    databaseURL: 'https://bitsmultiservice-default-rtdb.firebaseio.com',
    storageBucket: 'bitsmultiservice.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5IEigZmraXbiSlJ7_3CcCDRAAdT9_AJA',
    appId: '1:1050359172710:android:1d4027ccdd46dea46467a7',
    messagingSenderId: '1050359172710',
    projectId: 'bitsmultiservice',
    databaseURL: 'https://bitsmultiservice-default-rtdb.firebaseio.com',
    storageBucket: 'bitsmultiservice.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhJnU70UOuDfMH8AmycDPsm-r4MaaTjkM',
    appId: '1:1050359172710:ios:e7113139e808b5236467a7',
    messagingSenderId: '1050359172710',
    projectId: 'bitsmultiservice',
    databaseURL: 'https://bitsmultiservice-default-rtdb.firebaseio.com',
    storageBucket: 'bitsmultiservice.appspot.com',
    iosBundleId: 'com.example.groceryDeliverySide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhJnU70UOuDfMH8AmycDPsm-r4MaaTjkM',
    appId: '1:1050359172710:ios:e7113139e808b5236467a7',
    messagingSenderId: '1050359172710',
    projectId: 'bitsmultiservice',
    databaseURL: 'https://bitsmultiservice-default-rtdb.firebaseio.com',
    storageBucket: 'bitsmultiservice.appspot.com',
    iosBundleId: 'com.example.groceryDeliverySide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCujgUVu3pinxOeKzN0JtRulPbnJxHIgc',
    appId: '1:1050359172710:web:2c671d79810a453f6467a7',
    messagingSenderId: '1050359172710',
    projectId: 'bitsmultiservice',
    authDomain: 'bitsmultiservice.firebaseapp.com',
    databaseURL: 'https://bitsmultiservice-default-rtdb.firebaseio.com',
    storageBucket: 'bitsmultiservice.appspot.com',
  );

}