// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVxZ108LCEqAJTp4OYRct1uc7IylGeUtQ',
    appId: '1:857244758227:web:0271e56c14f3ba25d66426',
    messagingSenderId: '857244758227',
    projectId: 'grocery-a4d87',
    authDomain: 'grocery-a4d87.firebaseapp.com',
    storageBucket: 'grocery-a4d87.appspot.com',
    measurementId: 'G-JF6GRK7YY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm6Mn-nQ3mv7uY4bZ0ABNGaNLTDUJH_Go',
    appId: '1:857244758227:android:cc84525ffa683d93d66426',
    messagingSenderId: '857244758227',
    projectId: 'grocery-a4d87',
    storageBucket: 'grocery-a4d87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8XII2nzzc2suh_bzZf0G6tTEOTTf1_Ds',
    appId: '1:857244758227:ios:64a7ad1693f630cbd66426',
    messagingSenderId: '857244758227',
    projectId: 'grocery-a4d87',
    storageBucket: 'grocery-a4d87.appspot.com',
    iosBundleId: 'com.example.groceryDeliverySide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8XII2nzzc2suh_bzZf0G6tTEOTTf1_Ds',
    appId: '1:857244758227:ios:49458ae7c6b064e3d66426',
    messagingSenderId: '857244758227',
    projectId: 'grocery-a4d87',
    storageBucket: 'grocery-a4d87.appspot.com',
    iosBundleId: 'com.example.groceryDeliverySide.RunnerTests',
  );
}
